### ISSUE TITLE
Android only option

### ISSUE THREAD

**Issue by alaouy** [ain/smartbanner.js#13]
Hi there, Is there an option to only show the banner for android phones ?

**Comment by ain** [comment]
No, there is no such option.

AFAICS, you have 2 options:

1. Work with CSS based on `smartbanner--<platform>` class on the wrapper element
2. Implement something like `<meta name="smartbanner:enabled-platforms" content="android">` and send me a PR. If you choose to go with it, please add tests :)

**Comment by alaouy** [comment]
@ain working on a PR for this, and got an idea, how about just testing if the ios related meta tags(ie `button-url-apple icon-apple price-suffix-apple`) are not set without the need of an extra tag, for now if you don't set them it shows undefined

<img width="319" alt="capture d ecran 2016-09-23 a 13 44 04" src="https://cloud.githubusercontent.com/assets/3118889/18785957/4e9f5880-8193-11e6-8f5a-67c7dae1d5b0.png">

**Comment by ain** [comment]
`undefined` problem is a different topic. There I think an improvement could be made to avoid it and just prevent rendering, true. Should be a different ticket. Thanks.

As for digesting the data and deciding what to display, the main issue is that data distributes across several options, you'd need to walk through and keep registry so if all are missing, you could skip display in general. Then again, what if it is intentional to keep all those platform-specific bits empty?

For the reasons of transparency and robust behaviour, I would not use such analysation for display decision and go for a separate directive. I'm sure you agree.

**Comment by alaouy** [comment]
@ain I agree with you ain, I added a PR with this feature, and fixes to the test suite ;)

**Comment by ain** [comment]
Thanks for your work @alaouy, the feature has now landed in 1.1.0.
