### ISSUE TITLE
I don't want to show when already app installed!

### ISSUE THREAD

**Issue by irshadir7** [ain/smartbanner.js#149]
__Steps to reproduce__:

1.
2.
3.

__What happens__:

__What should happen__:

**Comment by irshadir7** [comment]
how to do it?

**Comment by ain** [comment]
Unfortunately this is currently not possible.

The original idea of `smartbanner.js` was to mimic the original [Apple's Smart App Banner](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) behaviour and offer additional customisations that would be easy to make. Also Apple's original implementation does not have this functionality.

Proposals in slightly overlapping areas have been made in #72, but there're privacy and stability concerns to such implementations which is why it is unlikely that this feature will be attempted.
