### ISSUE TITLE
position: absolute/fixed

### ISSUE THREAD

**Issue by paolobiavati** [ain/smartbanner.js#20]
hi, well done, very simple and fast.
I had a problem due to  `position:absolute`  in  `.smartbanner`  class.

Maybe it is done to hiding nothing from the original site, but for example, in my case I have a fixed header so... when the banner appear my body go down... i need a fixed smartbanner.
I don't like so much that  the function   `setContentPosition`   that put a margin-top on the html tag

I solved adding an attribute `data-smartbanner-original-margin-top="0"` in my html tag, so in `setContentPosition` function it enter in the if condition and do continue;

```
      if (wrapper.getAttribute(datas.originalMarginTop)) {
        continue;
      }
```

and overriding the position:absolute rule

```
.smartbanner {
	position: fixed;
}
```

thanks
cheers
Paolo

**Comment by ain** [comment]
Thanks a lot for the feedback Paolo.

Yes, smartbanner.js follows the official Apple behaviour that pushes all
content down.

I'm currently at WebSummit, but I will sure review your concern in the
first order and see if there's anything we could do better here.

**Comment by ain** [comment]
I've reviewed your issue. 

As said before, `smartbanner.js` was created to mimic [Apple's Smart App Banner](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) behaviour, but offer a fair amount of customisation options. Implementing fixed-positioning is therefore a bit out of scope.

As for your implementation, I don't think `data-smartbanner-original-margin-top` would be an appropriate option. `originalMarginTop` holds the original top margin of the body in order to restore it as soon as smartbanner has been closed. It shouldn't be used as an external option.

What we should debate is something like `data-smartbanner-position` that reflects CSS `position` of the smartbanner container so it can apply positioning logic accordingly.

I'll close this issue for now, but I'm happy to continue this discussion in a Pull Request that considers the above and has a more generic implementation for the positioning.
