### ISSUE TITLE
I'm interested in using your package for my Wordpress Plugin

### ISSUE THREAD

**Issue by mattpramschufer** [ain/smartbanner.js#27]
Hey there, I know this is probably not the best place to ask this.  I was looking for an email address for you or contact info, but couldn't find any.  Currently I have a Wordpress Plugin called AppBanners - https://wordpress.org/plugins/appbanners/  I am using https://github.com/jasny/jquery.smartbanner  as the sole driver for the plugin, but the author isn't updating and accepting pull requests, so I am looking for a replacement.  I found your project and think it would be an excellent replacement for jasny's script.  Before I did so, I just wanted to make sure it would be okay with you.

**Comment by ain** [comment]
Thanks for the heads up @mattpramschufer, nothing wrong with a question landing in the issues.

_smartbanner.js_ is Free Software licenced under [GPL-3](https://github.com/ain/smartbanner.js/blob/master/LICENSE). All open-source projects are more than welcome to implement it.

As for maintenance, I've had some very nice PRs by contributors, but they have and will take time to merge because every new feature has to be code-reviewed and tested. I have not accepted PRs that do not come with respective tests or fall out of scope. So the development is quite strict, but quality comes first.

If you need support with the implementation, please create a ticket as per subject.
