### ISSUE TITLE
Choose where to append/prepend.

### ISSUE THREAD

**Issue by partynikko** [ain/smartbanner.js#33]
Would it be possible to choose what element to append/prepend the smart banner to? Consider you want to have the smart banner inside another element, like a header, and not have it absolute positioned (which we obviously can change with CSS).

Right now it's automatically appended to the body tag which is not desired for all use cases.

If currently not supposed I would consider forking and then doing a pull-request.

**Comment by ain** [comment]
@nikkop thank you for the feedback.

Wouldn't #34 be sufficient in your case as well?

**Comment by jinoraL** [comment]
Hi ain,

I might be able to give a feedback. 

In my case, in fact,  [#34](https://github.com/ain/smartbanner.js/pull/34) is not sufficient. Since I have other elements in the body, the banner is placed after and is therefore positionned at the bottom of the page.

Prepending the smart banner to the body (and change with CSS its position as non absolute) actually solves the issue in my case. Adding an option to append or prepend the banner to the body in case of  enabled positionning would therefore be useful to solve my issue.

**Comment by ain** [comment]
`smartbanner`'s default behaviour is to appear at the top and push the rest of the content down. This is similar to Apple's original implementation. 

If you'd like to add a feature that'd allow custom appending/prepending behaviour, you're welcome to create a Pull Request. I'd suggest a new optional meta tags such as `smartbanner:append-target` and `smartbanner:prepend-target` which take a standard selector as valud and both of which automatically set `smartbanner:disable-positioning` to `true`.

Pull Request has to done so that:

- Default behaviour is not affected
- PR includes test for the added feature
- PR includes a feature documentation in [Advanced usage of README](https://github.com/ain/smartbanner.js#advanced-usage).

**Comment by jinoraL** [comment]
Referencing [here ](https://github.com/ioncmt/smartbanner.js/pull/1) the PR.

**Comment by ain** [comment]
@jinoraL I took a brief look and it does look good. Thanks for the work! There are just some beauty fixes to be done. 

In order to go further, please create new PR against the official repo here, not the fork. I'll the review in more detail and let's lamd tis feature!

**Comment by ain** [comment]
Closing this issue in order to avoid feature fatigue for the component that was originally meant to be robust.

Nevertheless, following combinations of [advanced features](https://github.com/ain/smartbanner.js#advanced-usage) can be used to achieve desired behaviour:

- [Disable position](https://github.com/ain/smartbanner.js#disable-positioning) for disabled automatic positioning
- [Custom design modifier](https://github.com/ain/smartbanner.js#custom-design-modifier) for using BEM methods 
- [API](https://github.com/ain/smartbanner.js#smartbanner-api-use) to control potential race conditions
