### ISSUE TITLE
There a delay before show ??

### ISSUE THREAD

**Issue by egphp** [ain/smartbanner.js#365]
I add meta and js at head

but its take time to load after page finish load

can i mange it to load faster ??

**Comment by ain** [comment]
Since the smartbanner loading depends on the loading of the page, try including JavaScript and CSS files in the `<head>` of your HTML. If you deploy critical CSS, try including it there.

In general the advice would be to optimise your page speed and Core Web Vitals in general. You can analyse and test your page by using https://web.dev
