### ISSUE TITLE
Browserify Issues

### ISSUE THREAD

**Issue by KyleBolton1** [ain/smartbanner.js#44]
I'm trying to use this script imported into a bundle in my project but when I try to import 'smartbanner.min.js' because it can't find the other requires/imports (which should they really be in a minified file?...) I get errors. 

"Cannot find module './polyfills/array/from.js" and basically swaps between them all (bakery.js, optionparser.js etc)

I know why it's happening, just not how to fix it. Even if I install the smartbanner.js into it's own folder the polyfills still aren't in the 'node_modules' folder. Probably something really silly but it's driving me crazy so any help would be appreciated!

**Comment by ain** [comment]
Thanks for the report @KyleBolton1. 

I'll look into this. I can see this is not behaving as it was meant to.

**Comment by KyleBolton1** [comment]
Thanks @ain!

**Comment by ain** [comment]
I've confirmed this is not a bug and is expected behaviour. The code in distribution (`dist/`) has already gone through browserify, see [package.json:38](https://github.com/ain/smartbanner.js/blob/master/package.json#L38).

Could you try passing `--noparse=<dist/smartbanner.js path>` to browserify so that _smartbanner_ code is not parsed on bundling? I'm guessing that might be your issue.

**Comment by KyleBolton1** [comment]
Yep, needed no parse. Cheers mate.
