### ISSUE TITLE
Crucial event emission for integration

### ISSUE THREAD

**Issue by ain** [ain/smartbanner.js#59]
It would be beneficial for 3rd party components if `smartbanner.js` emitted `smartbanner.exit` and `smartbanner.view` events on its container, e.g. for tracking purposes.

**Comment by jinoraL** [comment]
If PR #68 is merged, I might actually be able to propose a solution to have smartbanner.js dispatch the smartbanner.exit and smartbanner.view events on its container, i.e. on the element the smartbanner was appended or prepended. The container would listen to theses events and react accordingly (call 3rd party components like ga etc).

I can propose a PR to detail what I mean.

**Comment by ain** [comment]
Thanks! That’d be excellent @jinoraL! 

I’ll do my best to have it reviewed this week.

**Comment by oquis** [comment]
This would be awesome, right now I have a hack to solve this using [insertion-query](https://www.npmjs.com/package/insertion-query) to detect when I can attach said events to the buttons. While this works, it's far from perfect since I get some problems with it's solution using css animations.

I would also add a callback to handle a `smartbanner.display` event for tracking purposes

**Comment by ain** [comment]
@oquis thanks for the feedback. As you see the Pull Request was not merged due to the requests made. You're welcome to pick it up and finish it as by the Code Review on #68.
