### ISSUE TITLE
Fixed header

### ISSUE THREAD

**Issue by okankocyigit** [ain/smartbanner.js#67]
If we have a fixed header layout page, smartbanner is appears under that header.

Do you have a solution?

**Comment by ain** [comment]
Please post your meta tags that you're using to initialise `smartbanner.js`.

**Comment by shafaqat309** [comment]
App banner is appearing after fixed banner, here are my meta tags.

I accidentally closed the banner, how can I see that again?

    <meta name="smartbanner:title" content="app title">
    <meta name="smartbanner:author" content="my name">
    <meta name="smartbanner:price" content="FREE">
    <%--<meta name="smartbanner:price-suffix-apple" content=" - On the App Store">--%>
    <meta name="smartbanner:price-suffix-google" content=" - In Google Play">
    <%--<meta name="smartbanner:icon-apple" content="https://url/to/apple-store-icon.png">--%>
    <meta name="smartbanner:icon-google" content="url to googleplay.png">
    <meta name="smartbanner:button" content="VIEW">
    <%--<meta name="smartbanner:button-url-apple" content="https://ios/application-url">--%>
    <meta name="smartbanner:button-url-google" content="my app url">
    <%--<meta name="smartbanner:enabled-platforms" content="android,ios">--%>
    <meta name="smartbanner:enabled-platforms" content="android">
    <meta name="smartbanner:disable-positioning" content="true">
    <meta name="smartbanner:hide-ttl" content="10000">

**Comment by ain** [comment]
Given your configuration, this is expected behaviour since you have `smartbanner:disable-positioning` set to `true`. It is advanced feature that will disable smartbanner's standard positioning logic so the responsibility for positioning smartbanner lies on you and styles you apply yourself.

See [Disable positioning documentation](https://github.com/ain/smartbanner.js#disable-positioning) for more information.
