### ISSUE TITLE
Change button text to "Open" if app already installed

### ISSUE THREAD

**Issue by henbulls** [ain/smartbanner.js#7]
Hi Ain, 
Thanks for the awesome smartbanner code :)
can we change button text to "Open" if the app already installed ? And if click Open automatic opens the app.

**Comment by ain** [comment]
I did give it some thought in the beginning and the answer to your question is unfortunately negative. Changing the button to Open is not possible. It'd be a privacy problem since user's applications would be revealed to a website.

A very maximum that can be done, is to change the behaviour once user has tapped the button. There'd be a [hackish way](http://stackoverflow.com/questions/13044805/how-to-check-if-an-app-is-installed-from-a-web-page-on-an-iphone) to open the app if installed. On Android this hack would not work, it'd need [specific changes inside the application](http://stackoverflow.com/a/27274741/1373324).

We could debate iOS app opening behaviour in another ticket, but I am closing this one for the reasons listed.

**Comment by reetkamleshpoptani** [comment]
I also need this functionality on both ios and android to show open button instead of view button in case of app is already installed
