### ISSUE TITLE
Hide SmartBanner on desktops 

### ISSUE THREAD

**Issue by azelensky** [ain/smartbanner.js#8]
@ain , thank you for awesome SmartBanner once again.

How we can hide SmartBanner on Desktop computers? It should not be there by default, right? It is supposed to be on iOS/Android devices only.

Tested on iMac, Macbooks (the latest OSx, Chrom)

**Comment by ain** [comment]
Thanks for the ticket @azelensky, planned for a major version.

**Comment by azelensky** [comment]
it works perfectly. @ain, thank you very much!

**Comment by chiqui3d** [comment]
Hi, then No option to show on desktop?

**Comment by chiqui3d** [comment]
I used 
`<meta name="smartbanner:enabled-platforms" content="android,ios,desktop">
`
and not work

**Comment by ain** [comment]
Hi @chiqui3d, correct, there's no such platform as `desktop`. `smartbanner.js` provides the customisable smart app banners for iOS and Android, as it says in the description.

__Nevertheless__, since `v1.3.0`, thanks to great work by @fkoester, there's UA-specific targeting that allows you to define exact User Agent that should either be included or excluded. 

AFAIU you'd like to enable the banner everywhere so adding the following additional meta tag would deliver:

```html
<meta name="smartbanner:include-user-agent-regex" content=".*">
```

Feel free to adjust the `.*` regex to your (possibly more specific) needs. Please also see _Advanced usage_ in README.

**Comment by chiqui3d** [comment]
Hi @ain , thanks for the quick response, it totally serves me the example you have put me.

**Comment by mukeshghodela-easternts** [comment]
@ain Any way to show banner only on ios and android devices, not on desktops?

**Comment by ramaces** [comment]
Hi
i have this `<meta name="smartbanner:enabled-platforms" content="android,ios"> `
but it still showing on windows tab devices

**Comment by ramaces** [comment]
> @ain Any way to show banner only on ios and android devices, not on desktops?

I changed this
`else if (!window.MSStream && !/X11|Linux/i.test(userAgent) && maxTouchPoints && maxTouchPoints > 0 || /iPhone|iPad|iPod/i.test(userAgent)) {`
in to
`else if (!window.MSStream && !/X11|Linux|Windows/i.test(userAgent) && maxTouchPoints && maxTouchPoints > 0 || /iPhone|iPad|iPod/i.test(userAgent)) {`

now it doesn't show also on windows tab devices
